service: destinate-backend
# frameworkVersion: "=X.X.X"
provider:
  name: aws
  runtime: go1.x
  profile: personal
  stage: ${opt:stage, 'dev'}
  region: us-west-1
  deploymentBucket: destinate-deployment
  vpc:
    securityGroupIds:
      - sg-c32487ba
    subnetIds:
      - subnet-6b563b0c
#  iamRoleStatements:
  environment:
    DBHOST: destinate-backend-${opt:stage, 'dev'}.cmggb3cmze78.us-west-1.rds.amazonaws.com
package:
 exclude:
   - ./**
 include:
   - ./bin/**
functions:
  migrate:
    handler: bin/migrate
  # NOTE: desinations entity
  destinations-index:
    handler: bin/destinations-index
    events:
      - http:
          path: destinations
          method: get
  destinations-get:
    handler: bin/destinations-get
    events:
      - http:
          path: destinations/{id}
          method: get
          parameters:
            paths:
              id: true
  # NOTE: reviews entity
  reviews-index:
    handler: bin/reviews-index
    events:
      - http:
          path: reviews
          method: get
  reviews-post:
    handler: bin/reviews-post
    events:
      - http:
          path: reviews
          method: post
  reviews-get:
    handler: bin/reviews-get
    events:
      - http:
          path: reviews/{id}
          method: get
          parameters:
            paths:
              id: true
  reviews-put:
    handler: bin/reviews-put
    events:
      - http:
          path: reviews
          method: put
  reviews-delete:
    handler: bin/reviews-delete
    events:
      - http:
          path: reviews/{id}
          method: delete
          parameters:
            paths:
              id: true
  # NOTE: desinations entity
  users-index:
    handler: bin/users-index
    events:
      - http:
          path: users
          method: get
  users-post:
    handler: bin/users-post
    events:
      - http:
          path: users
          method: post
  users-get:
    handler: bin/users-get
    events:
      - http:
          path: users/{id}
          method: get
          parameters:
            paths:
              id: true
  users-put:
    handler: bin/users-put
    events:
      - http:
          path: users
          method: put
  users-delete:
    handler: bin/users-delete
    events:
      - http:
          path: users/{id}
          method: delete
          parameters:
            paths:
              id: true
  users-desinations-get:
    handler: bin/users-destinations-get
    events:
      - http:
          path: users/{id}/like/{did}
          method: get
          parameters:
            paths:
              id: true
              did: true
resources:
  Resources:
    deploymentBucket:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: BucketOwnerFullControl
        BucketName: destinate-deployment
    destinateBackendDatabase:
      Type: AWS::RDS::DBInstance
      Properties:
        AllocatedStorage: '20'
        DBInstanceClass: db.t2.micro
        DBName: destinate
        DBInstanceIdentifier: destinate-backend-${opt:stage, 'dev'}
        Engine: postgres
        MasterUsername: destinate
        MasterUserPassword: devPassword
        VPCSecurityGroups:
          - sg-c32487ba
